SELECT
	*
FROM
	ONLINE_RETAIL;

SELECT
	*
FROM
	ONLINE_RETAIL
WHERE
	CUSTOMERID IS NOT NULL
	AND INVOICENO NOT LIKE 'C%'
	AND STOCKCODE ~ '[0-9]'
	AND QUANTITY > 0
	AND UNITPRICE > 0;

CREATE TABLE ONLINE_RETAILS AS
SELECT
	*
FROM
	ONLINE_RETAIL
WHERE
	CUSTOMERID IS NOT NULL
	AND INVOICENO NOT LIKE 'C%'
	AND STOCKCODE ~ '[0-9]'
	AND QUANTITY > 0
	AND UNITPRICE > 0;

SELECT
	*
FROM
	ONLINE_RETAILS;

SELECT
	SUM(QUANTITY * UNITPRICE) TOTAL_REVENUE
FROM
	ONLINE_RETAILS;

SELECT
	COUNT(DISTINCT CUSTOMERID) TOTAL_CUSTOMER
FROM
	ONLINE_RETAILS;

ALTER TABLE ONLINE_RETAILS
ALTER COLUMN INVOICEDATE TYPE TIMESTAMP USING TO_TIMESTAMP(INVOICEDATE, 'MM/DD/YYYY HH24:MI');

WITH
	RECENCY AS (
		SELECT
			CUSTOMERID,
			'2011-12-10'::DATE - MAX(INVOICEDATE)::DATE AS RECENCY
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	FREQUENCY AS (
		SELECT
			CUSTOMERID,
			COUNT(DISTINCT INVOICENO) AS FREQUENCY
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	MONETARY AS (
		SELECT
			CUSTOMERID,
			SUM(QUANTITY * UNITPRICE) AS MONETARY
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	RFM_SCORING AS (
		SELECT
			R.CUSTOMERID,
			R.RECENCY,
			F.FREQUENCY,
			M.MONETARY,
			NTILE(4) OVER (
				ORDER BY
					RECENCY DESC
			) AS R_SCORE,
			NTILE(4) OVER (
				ORDER BY
					FREQUENCY
			) AS F_SCORE,
			NTILE(4) OVER (
				ORDER BY
					MONETARY
			) AS M_SCORE
		FROM
			RECENCY R
			JOIN FREQUENCY F ON R.CUSTOMERID = F.CUSTOMERID
			JOIN MONETARY M ON F.CUSTOMERID = M.CUSTOMERID
	),
	RFM_SEGMENTS AS (
		SELECT
			*,
			CASE
				WHEN R_SCORE = 4
				AND F_SCORE = 4
				AND M_SCORE = 4 THEN 'champions'
				WHEN R_SCORE >= 3
				AND F_SCORE >= 3 THEN 'loyal_Customers'
				WHEN R_SCORE = 1
				AND F_SCORE = 1 THEN 'Lost'
				WHEN R_SCORE <= 2
				AND F_SCORE <= 2 THEN 'hibernating'
				WHEN R_SCORE >= 2
				AND F_SCORE >= 2 THEN 'at_risk'
				WHEN R_SCORE <= 2
				AND F_SCORE >= 3 THEN 'cannot_lose_them'
				WHEN R_SCORE >= 4
				AND F_SCORE <= 2 THEN 'new_customers'
				WHEN R_SCORE = 3
				AND F_SCORE <= 2 THEN 'need_attention'
				ELSE 'others'
			END AS SEGMENTS
		FROM
			RFM_SCORING
	),
	CHURN_RISK AS (
		SELECT
			*,
			CASE
				WHEN RECENCY >= 180 THEN 'At_risk_of_churn'
				ELSE 'Active'
			END AS CHURN_RISKS
		FROM
			RFM_SEGMENTS
	),
	CHURN AS (
		SELECT
			*,
			CASE
				WHEN CHURN_RISKS = 'At_risk_of_churn' THEN 1
				ELSE 0
			END AS CHURN_FLAG
		FROM
			CHURN_RISK
	)
SELECT
	*
FROM
	CHURN;

WITH
	RECENCY AS (
		SELECT
			CUSTOMERID,
			'2011-12-10'::DATE - MAX(INVOICEDATE)::DATE AS RECENCY
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	FREQUENCY AS (
		SELECT
			CUSTOMERID,
			COUNT(DISTINCT INVOICENO) AS FREQUENCY
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	MONETARY AS (
		SELECT
			CUSTOMERID,
			SUM(QUANTITY * UNITPRICE) AS MONETARY
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	RFM_SCORING AS (
		SELECT
			R.CUSTOMERID,
			R.RECENCY,
			F.FREQUENCY,
			M.MONETARY,
			NTILE(4) OVER (
				ORDER BY
					RECENCY DESC
			) AS R_SCORE,
			NTILE(4) OVER (
				ORDER BY
					FREQUENCY
			) AS F_SCORE,
			NTILE(4) OVER (
				ORDER BY
					MONETARY
			) AS M_SCORE
		FROM
			RECENCY R
			JOIN FREQUENCY F ON R.CUSTOMERID = F.CUSTOMERID
			JOIN MONETARY M ON F.CUSTOMERID = M.CUSTOMERID
	),
	RFM_SEGMENTS AS (
		SELECT
			*,
			CASE
				WHEN R_SCORE = 4
				AND F_SCORE = 4
				AND M_SCORE = 4 THEN 'champions'
				WHEN R_SCORE >= 3
				AND F_SCORE >= 3 THEN 'loyal_Customers'
				WHEN R_SCORE = 1
				AND F_SCORE = 1 THEN 'Lost'
				WHEN R_SCORE <= 2
				AND F_SCORE <= 2 THEN 'hibernating'
				WHEN R_SCORE >= 2
				AND F_SCORE >= 2 THEN 'at_risk'
				WHEN R_SCORE <= 2
				AND F_SCORE >= 3 THEN 'cannot_lose_them'
				WHEN R_SCORE >= 4
				AND F_SCORE <= 2 THEN 'new_customers'
				WHEN R_SCORE = 3
				AND F_SCORE <= 2 THEN 'need_attention'
				ELSE 'others'
			END AS SEGMENTS
		FROM
			RFM_SCORING
	)
SELECT
	SEGMENTS,
	COUNT(CUSTOMERID) CUSTOMER_COUNT
FROM
	RFM_SEGMENTS
GROUP BY
	SEGMENTS
ORDER BY
	CUSTOMER_COUNT DESC;

WITH
	RECENCY AS (
		SELECT
			CUSTOMERID,
			'2011-12-10'::DATE - MAX(INVOICEDATE)::DATE AS RECENCY
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	FREQUENCY AS (
		SELECT
			CUSTOMERID,
			COUNT(DISTINCT INVOICENO) AS FREQUENCY
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	MONETARY AS (
		SELECT
			CUSTOMERID,
			SUM(QUANTITY * UNITPRICE) AS MONETARY
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	RFM_SCORING AS (
		SELECT
			R.CUSTOMERID,
			R.RECENCY,
			F.FREQUENCY,
			M.MONETARY,
			NTILE(4) OVER (
				ORDER BY
					RECENCY DESC
			) AS R_SCORE,
			NTILE(4) OVER (
				ORDER BY
					FREQUENCY
			) AS F_SCORE,
			NTILE(4) OVER (
				ORDER BY
					MONETARY
			) AS M_SCORE
		FROM
			RECENCY R
			JOIN FREQUENCY F ON R.CUSTOMERID = F.CUSTOMERID
			JOIN MONETARY M ON F.CUSTOMERID = M.CUSTOMERID
	),
	RFM_SEGMENTS AS (
		SELECT
			*,
			CASE
				WHEN R_SCORE = 4
				AND F_SCORE = 4
				AND M_SCORE = 4 THEN 'champions'
				WHEN R_SCORE >= 3
				AND F_SCORE >= 3 THEN 'loyal_Customers'
				WHEN R_SCORE = 1
				AND F_SCORE = 1 THEN 'Lost'
				WHEN R_SCORE <= 2
				AND F_SCORE <= 2 THEN 'hibernating'
				WHEN R_SCORE >= 2
				AND F_SCORE >= 2 THEN 'at_risk'
				WHEN R_SCORE <= 2
				AND F_SCORE >= 3 THEN 'cannot_lose_them'
				WHEN R_SCORE >= 4
				AND F_SCORE <= 2 THEN 'new_customers'
				WHEN R_SCORE = 3
				AND F_SCORE <= 2 THEN 'need_attention'
				ELSE 'others'
			END AS SEGMENTS
		FROM
			RFM_SCORING
	),
	CHURN_RISK AS (
		SELECT
			*,
			CASE
				WHEN RECENCY >= 180 THEN 'At_risk_of_churn'
				ELSE 'Active'
			END AS CHURN_RISKS
		FROM
			RFM_SEGMENTS
	),
	CHURN AS (
		SELECT
			*,
			CASE
				WHEN CHURN_RISKS = 'At_risk_of_churn' THEN 1
				ELSE 0
			END AS CHURN_FLAG
		FROM
			CHURN_RISK
	)
SELECT
	ROUND(AVG(CHURN_FLAG) * 100, 2)
FROM
	CHURN;

WITH
	INVOICE_MONTH AS (
		SELECT
			CUSTOMERID,
			DATE_TRUNC('month', INVOICEDATE)::DATE AS INVOICE_MONTH
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID,
			INVOICE_MONTH
	),
	FIRST_PURCHASE AS (
		SELECT
			CUSTOMERID,
			MIN(DATE_TRUNC('month', INVOICEDATE))::DATE AS FIRST_PURCHASE_MONTH
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	COHORT_INDEX AS (
		SELECT
			I.CUSTOMERID,
			INVOICE_MONTH,
			FIRST_PURCHASE_MONTH,
			(
				DATE_PART('year', AGE (INVOICE_MONTH, FIRST_PURCHASE_MONTH)) * 12 + DATE_PART(
					'month',
					AGE (INVOICE_MONTH, FIRST_PURCHASE_MONTH)
				)
			) AS COHORT_INDEX
		FROM
			INVOICE_MONTH I
			JOIN FIRST_PURCHASE F ON I.CUSTOMERID = F.CUSTOMERID
	),
	COHORT_COUNTS AS (
		SELECT
			FIRST_PURCHASE_MONTH,
			COHORT_INDEX,
			COUNT(DISTINCT CUSTOMERID) AS DISTINCT_CUSTOMERS
		FROM
			COHORT_INDEX
		GROUP BY
			FIRST_PURCHASE_MONTH,
			COHORT_INDEX
	),
	COHORT_SIZE AS (
		SELECT
			FIRST_PURCHASE_MONTH,
			COUNT(DISTINCT CUSTOMERID) COHORT_CUSTOMERS
		FROM
			COHORT_INDEX
		WHERE
			COHORT_INDEX = 0
		GROUP BY
			FIRST_PURCHASE_MONTH,
			COHORT_INDEX
	)
SELECT
	A.FIRST_PURCHASE_MONTH,
	COHORT_INDEX,
	COHORT_CUSTOMERS,
	ROUND(
		(DISTINCT_CUSTOMERS::DECIMAL / COHORT_CUSTOMERS) * 100,
		2
	) AS RETENTION_RATE
FROM
	COHORT_COUNTS A
	JOIN COHORT_SIZE B ON A.FIRST_PURCHASE_MONTH = B.FIRST_PURCHASE_MONTH;

WITH
	FREQUENCY AS (
		SELECT
			CUSTOMERID,
			COUNT(DISTINCT INVOICENO) AS FREQUENCY
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	MONETARY AS (
		SELECT
			CUSTOMERID,
			SUM(QUANTITY * UNITPRICE) AS MONETARY
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	AOV AS (
		SELECT
			F.CUSTOMERID,
			F.FREQUENCY,
			M.MONETARY,
			ROUND((M.MONETARY / F.FREQUENCY), 2) AS AOV
		FROM
			FREQUENCY F
			JOIN MONETARY M ON F.CUSTOMERID = M.CUSTOMERID
	),
	FIRST_PURCHASE AS (
		SELECT
			CUSTOMERID,
			MIN(DATE_TRUNC('month', INVOICEDATE))::DATE AS FIRST_PURCHASE_MONTH
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	LAST_PURCHASE AS (
		SELECT
			CUSTOMERID,
			MAX(DATE_TRUNC('month', INVOICEDATE))::DATE AS LAST_PURCHASE_MONTH
		FROM
			ONLINE_RETAILS
		GROUP BY
			CUSTOMERID
	),
	CUSTOMER_LIFESPAN AS (
		SELECT
			A.CUSTOMERID,
			FREQUENCY,
			MONETARY,
			A.AOV,
			DATE_PART(
				'year',
				AGE (LAST_PURCHASE_MONTH, FIRST_PURCHASE_MONTH)
			) * 12 + DATE_PART(
				'month',
				AGE (LAST_PURCHASE_MONTH, FIRST_PURCHASE_MONTH)
			) AS CUSTOMER_LIFESPAN
		FROM
			AOV A
			JOIN FIRST_PURCHASE FP ON A.CUSTOMERID = FP.CUSTOMERID
			JOIN LAST_PURCHASE LP ON LP.CUSTOMERID = A.CUSTOMERID
	)
SELECT
	CUSTOMERID,
	FREQUENCY,
	MONETARY,
	AOV,
	CUSTOMER_LIFESPAN,
	ROUND(
		(AOV * FREQUENCY * GREATEST(CUSTOMER_LIFESPAN, 1))::NUMERIC,
		2
	) AS CLV
FROM
	CUSTOMER_LIFESPAN
